version: '3.8'

services:
  # Ollama LLM service
  ollama:
    image: ollama/ollama:latest
    container_name: 2ndbrain-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - rag_network

  # 2ndBrain RAG application
  rag_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2ndbrain-rag
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./tests:/app/tests
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - RAG_FOLDER=/app/data
      - RAG_API_KEY=${RAG_API_KEY:-}
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - rag_network
    restart: unless-stopped

  # Optional: Nginx reverse proxy for HTTPS support
  nginx:
    image: nginx:alpine
    container_name: 2ndbrain-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rag_server
    networks:
      - rag_network
    restart: unless-stopped

networks:
  rag_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
